name: Demo 6 - Using secrets
on: push
jobs:
  first-job:
    env:
      EXAMPLE: ${{ secrets.EXAMPLE }}
    runs-on: ubuntu-latest
    steps:
      - name: Print the secret
        run: echo "Using secrets - example - ${{ env.EXAMPLE }}"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print the secret
        run: echo "Using secrets - example - ${{ env.EXAMPLE }}"
