name: 'Get & Cache Dependencies'
description: 'Get the dependencies via npm and cache them for later use'
inputs:
  should-cache:
    description: 'Whether to cache the dependencies or not.'
    required: false
    default: 'true'
outputs:
  has-used-cache:
    description: 'Whether the cache was used.'
    value: ${{ steps.log.outputs.cache }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.should-cache == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.should-cache != 'true'
      run: |
        npm ci
      shell: bash
    - name: Log dependencies status
      id: log
      run: | 
        echo "Dependencies downloaded - ${{ steps.install.outputs.cache-hit == 'false' }}"
        echo "::set-output name=cache::'${{ inputs.should-cache }}'"
      shell: bash
