name: Demo 14 - JS Action Deployment
on:
  push:
    branches:
      - main
jobs:
  information:
    runs-on: ubuntu-latest
    steps:
      - name: Run custom Action
        uses: ./.github/actions/deploy-s3-js
