name: Use Reusable Workflow
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies (lint)
        id: cache-lint
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache-lint.outputs.cache-hit != 'true'
        run: npm ci
      - name: Lint code
        run: npm run lint

  test:
    uses: ./.github/workflows/demo-11-reusable_test_workflow.yml
  build:
    needs: test
    runs-on: ubuntu-latest
    uses: ./.github/workflows/demo-11-reusable_build_workflow.yml
    with:
      build-command: 'npm run build-server'
  deploy:
    needs: build
    uses: ./.github/workflows/demo-11-reusable_deploy_workflow.yml
  report:
    needs: [lint, deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output Information
        run: |
          echo "Something went wrong"
          echo "{{ github }}"
