name: Branch Demo Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'dev-*'
      - 'feature/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo "${{ toJson(github.event) }}"
      - name: Get repo code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."

