# Make sure Github's access token is set in the repository settings,
# and that it has  the necessary scope permissions to manage workflows. When creating or updating a workflow file,
#  the token must have the "workflow" scope.
name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "First Workflow - Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
