name: Demo 6 - Using secrets
on: push
env:
  EXAMPLE: ${{ secrets.EXAMPLE }}
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print the secret
        run: echo "Using secrets - example - ${{ secrets.EXAMPLE }}"
